services:      
  whisper-ipex:
    volumes:
      - /mnt/ollama/whisper/models:/root/.cache/whisper
      - /mnt/ollama/whisper/whisper-files:/app
    networks:
      - llm-internal
      
  comfyui-ipex:
    volumes:
      - /mnt/ollama/comfyui/app:/app
      - /mnt/ollama/comfyui/python:/usr/local/lib/python3.10
    networks:
      - llm-internal

  ollama-sycl:
    volumes:
      - /mnt/ollama/ollama-data:/root/.ollama
      - /mnt/ollama/sycl-cache:/root/.cache
    networks:
      - llm-internal

  sdnext-ipex:
    volumes:
      - /mnt/ollama/sdnext/app:/app
      - /mnt/ollama/sdnext/mnt:/mnt
      - /mnt/ollama/sdnext/hugging-face:/root/.cache/huggingface
      - /mnt/ollama/sdnext/python:/usr/local/lib/python3.10
    networks:
      - llm-internal

  open-webui:
    volumes:
      - /mnt/ollama/open-webui:/app/backend/data
    networks:
      - traefik_network
      - llm-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`ai-chat.geth.systems`)"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    
networks:
  traefik_network:
    external: true
  llm-internal:
    external: true
